### ISSUE TITLE
Getting ??Disk pack error mounting Zork

### ISSUE THREAD

**Issue by aniellod** [agn453/RSTS-E#2]
Great work on putting this page together. 
Here's my problem:

System name:                     RSTS V10.1-L RSTS/E V10.1

$ mount dl3:/override
??Disk pack mount error
$ 

(simh file)
; DL3: 
set rl3 rl03
att rl3 rl02-zemu25.dsk

What am I doing wrong?

**Comment by agn453** [comment]
The ZEMU disk image is in RT-11 format and cannot be mounted as a native RSTS format disk with the MOUNT command.  Also, I assume you mistyped your entry from the simh initialisation file - the type of disk should be RL02 and not "rl03".

To access the files from an RT-11 formatted disk, you need to use the FIT program.  There is an updated binary of ```FIT.TSK``` that corrects a date issue (see the README.md file).  Once you've installed this you can use commands like -

```
$ allocate dl3:
$ fit dl3:/rt/li
```

to list the RT-11 directory.

If you get an error like "?Not a valid device", then you will need to do a SYSGEN to configure at least four DL disk devices into the running monitor (I'm not sure if this is the default - there may only be 2 units available and ```$ show dev dl``` will confirm this).

To copy the files onto the RSTS system disk, I suggest you create a user account specifically for them, then copy all the files across using FIT.  (again, the README.md has sample commands).

You should look at the ```ZEMU.DOC``` file for details on how to get it running.

Tony

**Comment by aniellod** [comment]
Thanks Tony for answering my silly question so quickly. I thought RL was the disk type and the number simply the disk number.

**Comment by agn453** [comment]
The only silly question is the one you don't ask.

By the way, I realised getting the updated FIT program onto a system without DECnet networking or Kermit (serial line file transfer) is difficult.  There's a copy of the updated sourcecode for FIT on the ZEMU disk too.  You can get it installed (assuming the rl02-zemu25.dsk is attached to rl3) using -

```
$ allocate dl3:
$ fit sy:fit.bas=dl3:fit.bas/rt
$ fit sy:fitbld.com=dl3:fitbld.com/rt
$ @fitbld
$ rename auxlib$:fit.tsk auxlib$:fitold.tsk
$ copy fit.tsk auxlib$:
$ deallocate dl3:
```
